print('Hello! Welcome to Budget-Sim 2000!')
inc = int(input('Please input your total net income: '))
hos = float(input('How much is rent? '))
food = float(input('What are your food costs? '))
bus = float(input('What is your total transportation costs? '))
cell = float(input('How much is your phone bill? '))
uti = float(input('How much do you pay on utilities? '))
pants = float(input("What do you spend on clothes?"))
hos_pc = format(hos / inc, '.2%')
food_pc = format(food / inc, '.2%')
bus_pc = format(bus / inc, '.2%')
cell_pc = format(cell / inc, '.2%')
uti_pc = format(uti / inc, '.2%')
pants_pc = format(pants / inc, '.2%')
cash = float(inc - hos - food - bus - cell - uti - pants)
print('Your total income is $' + str(format(inc, ',.2f')))
print('Your housing is ' + str(hos_pc) + ' of your income,')
print('food is ' + str(food_pc) + ',')
print('transportation is ' + str(bus_pc) + ',')
print('phone costs ' + str(cell_pc) + ',')
print('utilities are ' + str(uti_pc) + ',')
print('and clothing is ' + str(pants_pc) + ' of your total income.')
print('after expenses are paid you have $' + str(format(cash, ',.2f')) + ' to buy anything you want.')
