#  Variables
laboratories = input("What is your name? ")
date_of_birth = input("In mmddyyyy format, when were you born?")
reward = input("What would you describe being thrown into a fire as?")
note = input("What is something you would come back to?")
success_level = input("What is your amount of accomplishment during the tests?")
emotion_1 = input("What feeling did the fire you were thrown into give you?")
determination = input("Why must you succeed in testing?")
outsiders = input("Who might you leave behind?")
advice = input("Complete the sentence 'there's no sense crying...'")
cake = input("What is your motivation and also delicious and moist?")
Science_again = input("Why are you here?")
moar_science = input("What can teleport you from A to B?")
Living = input("How does science make you feel?")
#  Mad Libs result
print(laboratories + " Science - Still Alive")
print("Forms FORM-" + date_of_birth + "-12")
print("Test Assessment Report")
print("This was " + reward)
print("I'm making a " + note + " here:")
print(success_level + " SUCCESS.")
print("It's hard to overstate")
print("my " + emotion_1 + ".")
print(laboratories + " Science")
print("We do what we must")
print("because " + determination + ".")
print("For the good of all of us")
print("Except the ones who are " + outsiders + ".")
print("But there's no sense crying")
print(advice + ".")
print("You just keep on trying")
print("till you run out of " + cake + ".")
print("And the " + Science_again + " gets done,")
print("And you make " + moar_science + ",")
print("For the people who are")
print("still " + Living + ".")
