print("Aperature Science - Still Alive")
print("Forms FORM-29827281-12")
print("Test Assessment Report")
print("This was a triumph")
print("I'm making a note here:")
print("HUGE SUCCESS.")
print("It's hard to overstate")
print("my satisfaction.")
print("Aperature Science")
print("We do what we must")
print("because we can.")
print("For the good of all of us")
print("Except the ones who are dead.")
print("But there's no sense crying")
print("over every mistake.")
print("You just keep on trying")
print("till you run out of cake.")
print("And the science gets done,")
print("And you make a neat gun,")
print("For the people who are")
print("still alive.")
